project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - ttprojects.qmd
    - projects/tidy-tuesday-20250304.Rmd
    - projects/tidy-tuesday-20250311.Rmd
    - projects/tidy-tues-wk11.qmd

website:
  title: "Henry Owens"
  site-url: https://hankowens.github.io/
  navbar:
    left:
      - href: index.html
        text: Home
      - href: ttprojects.html
        text: Projects

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
