project:
  type: website
  output-dir: docs

website:
  title: "Henry Owens"
  site-url: https://hankowens.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/tidy-tuesday-20250304.html
        text: Tidy Tuesday 2025-03-04

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



