project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - projects/tidy-tuesday-20250304.Rmd

website:
  title: "Henry Owens"
  site-url: https://hankowens.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/tidy-tuesday-20250304.html
        text: Tidy Tuesday 2025-03-04

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



